[phases.setup]
php_version = "8.3"

[phases.install]
commands = [
    "composer install --ignore-platform-reqs"
]

[phases.build]
commands = [
    "php artisan optimize",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[phases.start]
commands = [
    "php-fpm8 -F -R -y /etc/php/8.3/fpm/php-fpm.conf -O"
]
